name: have_app
description: It plugin does works with applications installed on devices.
version: 0.0.3
repository: https://github.com/LeonardoRosaa/have_app

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.leonardo.have_app
        pluginClass: HaveAppPlugin
